version: '3.8'

services:
  app:
    image: ruby:3.2.1
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./demo:/app/demo
    command:
      - sh
      - -c
      - |
        gem install rails
        cd /app/demo/blog
        bundle install
        rails s -p 3000 -b '0.0.0.0'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command:
      - sh
      - -c
      - |
        service nginx restart
        tail -f /dev/null
    depends_on:
      - app

